/* GENERATED by scripts/cutout-partner-logos.mjs. Do not edit by hand:
   re-run the script, which rewrites this file from the processed logos.

   Pixel size and marquee treatment of every partner logo after the canvas
   was cut away and the file trimmed. Keyed by slug, not path, because in
   production the image URL is a Sanity CDN URL.
     mark     transparent cutout, sized by equal area
     badge    a full-bleed coloured plate, shown at one height with a radius
     artwork  photographic, kept off the marquee */

export type LogoTreatment = "mark" | "badge" | "artwork";

export interface PartnerLogoGeometry {
  w: number;
  h: number;
  treatment: LogoTreatment;
}

export const partnerLogoSizes: Record<string, PartnerLogoGeometry> = {
  "7l": { w: 121, h: 110, treatment: "mark" },
  "a-cube": { w: 151, h: 118, treatment: "mark" },
  "alvaro-castagnino": { w: 145, h: 105, treatment: "mark" },
  "amidhara": { w: 182, h: 132, treatment: "mark" },
  "azzurro": { w: 189, h: 110, treatment: "mark" },
  "bad-boys": { w: 138, h: 139, treatment: "mark" },
  "beevee": { w: 257, h: 47, treatment: "mark" },
  "believe-in-shirts": { w: 162, h: 142, treatment: "mark" },
  "biba": { w: 181, h: 138, treatment: "badge" },
  "blazo": { w: 174, h: 116, treatment: "mark" },
  "bonny": { w: 138, h: 125, treatment: "mark" },
  "caroline-clothing": { w: 183, h: 112, treatment: "artwork" },
  "catwalk": { w: 265, h: 72, treatment: "mark" },
  "charter": { w: 181, h: 83, treatment: "mark" },
  "chocolate-baby": { w: 270, h: 43, treatment: "mark" },
  "clubwear": { w: 194, h: 33, treatment: "mark" },
  "cool-colors": { w: 185, h: 78, treatment: "mark" },
  "country-wide-shirts": { w: 278, h: 90, treatment: "mark" },
  "cross-world": { w: 107, h: 151, treatment: "mark" },
  "dagerrfly": { w: 165, h: 66, treatment: "mark" },
  "dare-jeans": { w: 205, h: 112, treatment: "mark" },
  "deal-jeans": { w: 224, h: 55, treatment: "mark" },
  "dhwaja": { w: 76, h: 109, treatment: "mark" },
  "dida": { w: 246, h: 90, treatment: "badge" },
  "ethniks-neu-ron": { w: 174, h: 150, treatment: "badge" },
  "exceed": { w: 259, h: 35, treatment: "mark" },
  "focus-jeans": { w: 221, h: 79, treatment: "badge" },
  "four-buttons": { w: 219, h: 142, treatment: "badge" },
  "gemini": { w: 217, h: 118, treatment: "mark" },
  "grab-it": { w: 168, h: 93, treatment: "mark" },
  "hatchers": { w: 170, h: 57, treatment: "mark" },
  "hoffmen": { w: 233, h: 61, treatment: "mark" },
  "indian-terrain": { w: 130, h: 143, treatment: "mark" },
  "integriti": { w: 195, h: 83, treatment: "badge" },
  "juliet": { w: 171, h: 151, treatment: "badge" },
  "juniper": { w: 163, h: 43, treatment: "mark" },
  "kashmiera": { w: 162, h: 64, treatment: "mark" },
  "kathy": { w: 225, h: 84, treatment: "mark" },
  "kidzello": { w: 105, h: 116, treatment: "mark" },
  "kooki-ethnics": { w: 158, h: 123, treatment: "mark" },
  "la-scoot": { w: 181, h: 140, treatment: "badge" },
  "libas": { w: 181, h: 140, treatment: "badge" },
  "little-collars": { w: 185, h: 129, treatment: "mark" },
  "little-kangaroos": { w: 168, h: 109, treatment: "mark" },
  "mayur": { w: 241, h: 160, treatment: "artwork" },
  "mikki-house": { w: 202, h: 87, treatment: "mark" },
  "minerals-jeans": { w: 161, h: 131, treatment: "mark" },
  "mj-mashup": { w: 149, h: 143, treatment: "badge" },
  "mohit-industries": { w: 137, h: 175, treatment: "mark" },
  "mollys": { w: 169, h: 143, treatment: "badge" },
  "nivia": { w: 172, h: 86, treatment: "mark" },
  "nostrum": { w: 223, h: 56, treatment: "badge" },
  "obaby": { w: 190, h: 115, treatment: "mark" },
  "octave": { w: 270, h: 38, treatment: "mark" },
  "peppermint": { w: 202, h: 115, treatment: "mark" },
  "perri-palley": { w: 229, h: 69, treatment: "mark" },
  "pretty-woman": { w: 270, h: 74, treatment: "badge" },
  "raksha": { w: 269, h: 59, treatment: "mark" },
  "rangriti": { w: 219, h: 78, treatment: "mark" },
  "raw-star": { w: 178, h: 105, treatment: "badge" },
  "re-pink": { w: 261, h: 141, treatment: "badge" },
  "red-flame": { w: 180, h: 143, treatment: "badge" },
  "rexstraut-jeans": { w: 223, h: 98, treatment: "badge" },
  "skechers": { w: 505, h: 49, treatment: "mark" },
  "spykar": { w: 234, h: 63, treatment: "mark" },
  "stori": { w: 218, h: 102, treatment: "badge" },
  "sulphur-style-lab": { w: 168, h: 120, treatment: "mark" },
  "sweet-dreams": { w: 405, h: 104, treatment: "badge" },
  "tadpole": { w: 237, h: 88, treatment: "mark" },
  "tassel": { w: 182, h: 133, treatment: "badge" },
  "tiny-girl": { w: 216, h: 60, treatment: "badge" },
  "twills": { w: 225, h: 53, treatment: "badge" },
  "vriti": { w: 165, h: 84, treatment: "mark" },
  "wildcraft": { w: 222, h: 121, treatment: "mark" },
  "yaaron": { w: 160, h: 63, treatment: "mark" },
  "yvon-satin": { w: 199, h: 82, treatment: "mark" },
  "zola": { w: 273, h: 156, treatment: "badge" },
};
